#+TITLE: Final Countdown
[[https://travis-ci.org/Lodifice/final-countdown][https://travis-ci.org/Lodifice/final-countdown.svg?branch=master]]
* Concept
  The fame of Final Countdown is a meme, because no one knows any other song
  by Europe. The same is the case for many other bands. This project attempts
  to create a list of the single best song of every more or less popular
  band. For now it's only a playlist, but I might create a service to embed
  it into popular music software later. The current list is [[./playlist.org][here]].
* Contribution
** Suggestions (band and song)
   Create a pull request for ~playlist.org~. I will only accept pull requests
   that
   - preserve the structure of the Org file
   - preserve the alphabetical order
   - use spaces instead of tabs for indentation
** Requests for new bands (without giving a song)
   [[https://github.com/Lodifice/final-countdown/issues/new?template=Feature_request.md][Create an issue]].
** Change requests for bands that are already in the list
   [[https://github.com/Lodifice/final-countdown/issues/new?template=Bug_report.md][Create an issue]].
* Want to listen to the goodness?
  It's now possible to do so on [[https://open.spotify.com/user/marauderxtreme/playlist/7q3YCs5ioZhIMbZpVUknEf][Spotify]] or [[https://music.apple.com/playlist/pl.u-xK8PUpKJag7][Apple Music]].
  It gets updated fairly regular after every Pull Request goes through.
  Don't have Spotify but want to have a look at the current state? I got you [[https://open.spotify.com/embed/user/marauderxtreme/playlist/7q3YCs5ioZhIMbZpVUknEf][covered]].
* License
   [[./LICENSE][CC0]]
